# This config file defines the agents and their configurations for the MCP servers. E
# The key structure is:
# AgentName: # The name of the agent, e.g., "AppAgent", "HostAgent", "HardwareAgent"
#   sub_type: # The sub type of the agent, can be "default" or the app root name. 
  #   data_collection: # The data collection server list configuration for the agent. Fixed name.
  #   - namespace: # The namespace of the server.
  #   - type: # The type of the server, can be "stdio" or "http".
  #   - start_args: # The start arguments for the server. Only used for stdio servers.
  #   - host: # The host of the server, only used for http servers.
  #   - port: # The port of the server, only used for http servers.
  #   - path: # The path of the server, only used for http servers.
  #  action: # The action configuration server list for the agent. Fixed name.
  #   ...(same structure as data_collection)


HostAgent:
  default:
    data_collection:
      - namespace: DesktopUICollector
        type: stdio
        start_args: []
    action:
      - namespace: DesktopUIExecutor
        type: stdio
        start_args: []
      - namespace: CommandLineExecutor
        type: stdio
        start_args: []


AppAgent:
  default:
    data_collection:
      - namespace: AppUICollector
        type: stdio
        start_args: []
    action:
      - namespace: AppUIExecutor
        type: stdio
        start_args: []
  WINWORD.EXE:
    data_collection:
      - namespace: AppUICollector
        type: stdio
        start_args: []
    action:
      - namespace: AppUICollector
        type: stdio
        start_args: []
      - namespace: WordCOMExecutor
        type: stdio
        start_args: []
    EXCEL.EXE:
      data_collection:
        - namespace: AppUICollector
          type: stdio
          start_args: []
      action:
        - namespace: AppUICollector
          type: stdio
          start_args: []
        - namespace: ExcelCOMExecutor
          type: stdio
          start_args: []
    POWERPNT.EXE:
      data_collection:
        - namespace: AppUICollector
          type: stdio
          start_args: []
      action:
        - namespace: AppUICollector 
          type: stdio
          start_args: []
        - namespace: PowerPointCOMExecutor
          type: stdio
          start_args: []
    msedge.exe:
      data_collection:
        - namespace: AppUICollector
          type: stdio
          start_args: []
      action:
        - namespace: AppUICollector
          type: stdio
          start_args: []
        - namespace: WebExecutor
          type: stdio
          start_args: []
    chrome.exe:
      data_collection:
        - namespace: AppUICollector
          type: stdio
          start_args: []
      action:
        - namespace: AppUICollector
          type: stdio
          start_args: []
        - namespace: WebExecutor
          type: stdio
          start_args: []


HardwareAgent:
  default:
    data_collection:
      - namespace: HardwareCollector
        type: http
        host: "localhost"
        port: 8006
        path: "/mcp"
    action:
      - namespace: HardwareExecutor
        type: http
        host: "localhost"
        port: 8006
        path: "/mcp"

    
