HostAgent:
  default:
    data_collection:
      - namespace: DesktopUICollector
        type: local
        start_args: []
    action:
      - namespace: DesktopUIExecutor
        type: local
        start_args: []
      - namespace: CommandLineExecutor
        type: local
        start_args: []


AppAgent:
  default:
    data_collection:
      - namespace: AppUICollector
        type: local
        start_args: []
    action:
      - namespace: AppUIExecutor
        type: local
        start_args: []
  WINWORD.EXE:
    data_collection:
      - namespace: AppUICollector
        type: local
        start_args: []
    action:
      - namespace: AppUICollector
        type: local
        start_args: []
      - namespace: WordCOMExecutor
        type: local
        start_args: []
    EXCEL.EXE:
      data_collection:
        - namespace: AppUICollector
          type: local
          start_args: []
      action:
        - namespace: AppUICollector
          type: local
          start_args: []
        - namespace: ExcelCOMExecutor
          type: local
          start_args: []
    POWERPNT.EXE:
      data_collection:
        - namespace: AppUICollector
          type: local
          start_args: []
      action:
        - namespace: AppUICollector 
          type: local
          start_args: []
        - namespace: PowerPointCOMExecutor
          type: local
          start_args: []
    msedge.exe:
      data_collection:
        - namespace: AppUICollector
          type: local
          start_args: []
      action:
        - namespace: AppUICollector
          type: local
          start_args: []
        - namespace: WebExecutor
          type: local
          start_args: []
    chrome.exe:
      data_collection:
        - namespace: AppUICollector
          type: local
          start_args: []
      action:
        - namespace: AppUICollector
          type: local
          start_args: []
        - namespace: WebExecutor
          type: local
          start_args: []


HardwareAgent:
  default:
    data_collection:
      - namespace: HardwareCollector
        type: http
        host: "localhost"
        port: 8006
        path: "/mcp"
    action:
      - namespace: HardwareExecutor
        type: http
        host: "localhost"
        port: 8006
        path: "/mcp"

    
