CONTROL_BACKEND: "uia"  # The backend for control action
MAX_STEP: 30  # The max step limit for completing the user request
SLEEP_TIME: 5  # The sleep time between each step to wait for the window to be ready
SAFE_GUARD: True  # Whether to use the safe guard to prevent the model from doing sensitve operations.
CONTROL_TYPE_LIST: ["Button", "Edit", "TabItem", "Document", "ListItem", "MenuItem", "ScrollBar", "TreeItem", "Hyperlink", "ComboBox", "RadioButton", "DataItem"]  # The list of control types that are allowed to be selected 
HISTORY_KEYS: ["Step", "Thought", "ControlText", "Action", "Comment", "Results"]  # The keys of the action history for the next step.
ANNOTATION_COLORS: {
        "Button": "#FFF68F",
        "Edit": "#A5F0B5",
        "TabItem": "#A5E7F0",
        "Document": "#FFD18A",
        "ListItem": "#D9C3FE",
        "MenuItem": "#E7FEC3",
        "ScrollBar": "#FEC3F8",
        "TreeItem": "#D6D6D6",
        "Hyperlink": "#91FFEB",
        "ComboBox": "#D8B6D4"
    }

PRINT_LOG: False  # Whether to print the log  
CONCAT_SCREENSHOT: False  # Whether to concat the screenshot for the control item
LOG_LEVEL: "DEBUG"  # The log level
INCLUDE_LAST_SCREENSHOT: True  # Whether to include the last screenshot in the observation
REQUEST_TIMEOUT: 250  # The call timeout for the GPT-V model


HOSTAGENT_PROMPT: "ufo/prompts/base/{mode}/host_agent.yaml"  # The prompt for the app selection
# Due to the limitation of input size, lite version of the prompt help users have a taste. And the path is "ufo/prompts/base/lite/{mode}/host_agent.yaml"
APPAGENT_PROMPT: "ufo/prompts/base/{mode}/app_agent.yaml"  # The prompt for the action selection
# Lite version: "ufo/prompts/base/lite/{mode}/app_agent.yaml"

HOSTAGENT_EXAMPLE_PROMPT: "ufo/prompts/examples/{mode}/host_agent_example.yaml"  # The prompt for the app selection
# Lite version: "ufo/prompts/examples/lite/{mode}/host_agent_example.yaml"
APPAGENT_EXAMPLE_PROMPT: "ufo/prompts/examples/{mode}/app_agent_example.yaml"  # The prompt for the action selection
# Lite version: "ufo/prompts/examples/lite/{mode}/app_agent_example.yaml"

## For experience learning
EXPERIENCE_PROMPT: "ufo/prompts/experience/{mode}/experience_summary.yaml"
EXPERIENCE_SAVED_PATH: "vectordb/experience/"

## For user demonstration learning
DEMONSTRATION_PROMPT: "ufo/prompts/demonstration/{mode}/demonstration_summary.yaml"
DEMONSTRATION_SAVED_PATH: "vectordb/demonstration/"

API_PROMPT: "ufo/prompts/base/{mode}/api.yaml"  # The prompt for the API
INPUT_TEXT_API: "type_keys" # The input text API
INPUT_TEXT_ENTER: True # whether to press enter after typing the text
